from scrapers.indeed import resolve_indeed_url, search_indeed_jobs
from scrapers.linkedin import search_linkedin_jobs
from scrapers.naukri import search_naukri_jobs
from scrapers.remoteok import search_remoteok_jobs
from scrapers.serpapi_jobs import check_serpapi_available, search_serpapi_jobs
from scrapers.web_search import search_web_for_jobs
